### ISSUE TITLE
Noting an old repositry containing an experimental full 3D route viewer for OpenBVE content

### ISSUE THREAD

**Issue by afarlie** [BVE-Reborn/bve-reborn-archive#3]
I'd noted this older repository on the main OpenBVE one:- 
https://github.com/leezer3/OpenBVE/issues/93

**Comment by afarlie** [comment]
I'd also found some sources for a text editor written as a developer tool for Open BVE.
https://github.com/leezer3/OpenBVE/issues/94

Uniquely for a text editor it has an import option I've not been able to find anywhere else, in respect of various non Latin coedpages.

**Comment by cwfitzgerald** [comment]
I don't particularly see what the purpose of this text editor is considering most modern text editors have support for UTF-8 and a variety of other encodings. I know my editor SublimeText has support for many code pages.

**Comment by afarlie** [comment]
This was the C# text editor Michelle wrote.  If other editors already support the required functionality.

**Comment by cwfitzgerald** [comment]
I think because most modern editors support UTF-8, we really need a converter from all the various encodings to UTF-8 so that more obscure encodings can be manipulated. That wouldn't be that hard to build and could be part of the tool suite. 
---
Connor Fitzgerald
